### ISSUE TITLE
SMTP authentication failure when the app sends emails for account confirmation etc.

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#144]
**Status:** A temporary fix has been implemented and deployed.

A user has reported that sign up form no longer works (it produces a generic error message).

The following extract from *log/production.log* shows it is due to an SMTP authentication failure when sending the confirmation email from our @gmail.com account:

```
Net::SMTPAuthenticationError (535-5.7.8 Username and Password not accepted. Learn more at
):
  app/controllers/accounts/registrations_controller.rb:6:in `create'
  lib/rack/response_timer.rb:12:in `_call'
  lib/rack/response_timer.rb:7:in `call'
```

(The SMTP response is cut off, but apparently just links to https://support.google.com/mail/?p=BadCredentials which isn't very helpful.)

The problem is that Google recently stopped allowing username-and-password authentication for third-party apps (the "Allow less secure apps" option):

> To help keep your account secure, from May 30, 2022, Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.  
> —https://support.google.com/accounts/answer/6010255

I implemented and deployed a temporary workaround in the branch 'hotfix-email' ([commits](https://github.com/NZOI/nztrain/compare/743679784bebc5bc2a37e7e10d83bef6d033395d...a54b2ca6a61344cfe30c79893ed678c72efb3eb9)). The workaround is to write the emails to a file and ask users to contact us so we can manually send them the confirmation link.

To fix this properly we plan to enable 2-step verification for the app's Gmail account, which makes it possible to generate an app-specific password (https://support.google.com/accounts/answer/185833). Authentication using an app-specific password is still supported. This process is currently delayed because the account's recovery details need to be updated, and [this can take a week](https://support.google.com/accounts/answer/3463280).

Another approach is to switch to OAuth for authentication, but that's complicated.

**Comment by tom93** [comment]
Status update:
We are still working on enabling 2-step verification.
Meanwhile, I implemented an improved version of the temporary workaround in #145 (not deployed yet).

**Comment by tom93** [comment]
This has now been fixed properly by enabling 2-step verification and generating an app-specific password.
I reverted the temporary workarounds and verified that mail delivery works.
